groups:
    - developers
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: sahli-interactive-loris
    homebrewalt:
        apps:
            - git-extras
